apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  rules:
    - host: yourdomain.com
      http:
        paths:
          - path: /api/django
            backend:
              serviceName: django-service
              servicePort: 80
          - path: /api/flask
            backend:
              serviceName: flask-service
              servicePort: 80
