apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-service
spec:
  replicas: 3  # Number of instances
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: django-image
