# Generated by Django 4.2.16 on 2024-11-15 01:14

from django.db import migrations, models
import notes.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(validators=[notes.models.validate_not_empty]),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=255, validators=[notes.models.validate_not_empty]),
        ),
    ]
